const properties = [
  {
    title: 'Luxury 3BHK Apartment in Baner',
    description: 'Spacious and well-ventilated 3BHK apartment in the heart of Baner with modern amenities, 24/7 security, and stunning city views.',
    price: 8500000,
    type: 'sale',
    category: 'apartment',
    status: 'available',
    location: {
      address: '12, Palm Grove Society, Baner Road',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411045',
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      area: 1450,
      parking: true,
      furnished: 'semi-furnished',
      amenities: ['Gym', 'Swimming Pool', 'Clubhouse', 'Children Play Area'],
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800', filename: 'sample1' },
    ],
    featured: true,
  },
  {
    title: 'Modern Villa in Koregaon Park',
    description: 'Elegant 4BHK villa with private garden, modular kitchen, and premium finishes in the most sought-after locality of Pune.',
    price: 25000000,
    type: 'sale',
    category: 'villa',
    status: 'available',
    location: {
      address: '7, Rose Lane, Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411001',
    },
    features: {
      bedrooms: 4,
      bathrooms: 4,
      area: 3200,
      parking: true,
      furnished: 'fully-furnished',
      amenities: ['Private Garden', 'Jacuzzi', 'Home Theater', 'Solar Panels'],
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800', filename: 'sample2' },
    ],
    featured: true,
  },
  {
    title: '2BHK Apartment for Rent in Hinjewadi',
    description: 'Fully furnished 2BHK near IT hub in Hinjewadi. Ideal for IT professionals. Close to all tech parks.',
    price: 25000,
    type: 'rent',
    category: 'apartment',
    status: 'available',
    location: {
      address: '45, Phase 1, Hinjewadi IT Park Road',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411057',
    },
    features: {
      bedrooms: 2,
      bathrooms: 2,
      area: 1100,
      parking: true,
      furnished: 'fully-furnished',
      amenities: ['Power Backup', 'Security', 'Lift', 'WiFi Ready'],
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', filename: 'sample3' },
    ],
    featured: false,
  },
  {
    title: 'Commercial Office Space in Viman Nagar',
    description: 'Prime commercial space ideal for startups and corporate offices with excellent connectivity and modern infrastructure.',
    price: 45000,
    type: 'rent',
    category: 'office',
    status: 'available',
    location: {
      address: 'Business Hub, Viman Nagar',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
      pincode: '411014',
    },
    features: {
      bedrooms: 0,
      bathrooms: 2,
      area: 2000,
      parking: true,
      furnished: 'semi-furnished',
      amenities: ['Conference Room', 'Cafeteria', '24x7 Access', 'CCTV'],
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800', filename: 'sample4' },
    ],
    featured: false,
  },
];

module.exports = { properties };
